services:
  # 只启动数据库，其他服务在本地运行
  db:
    image: mysql:8.0
    container_name: market-pulse-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-market_pulse_db}
      MYSQL_USER: ${DB_USER:-market_pulse_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wBYXZkiLTExiEAHF}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data-dev:/var/lib/mysql
    networks:
      - market-pulse-network

volumes:
  mysql-data-dev:
    driver: local 

networks:
  market-pulse-network:
    driver: bridge 
