name: Deploy to Server

on:
  push:
    branches: [ main, master ]  # 当代码推送到 main 或 master 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 清理目标目录
            rm -rf /www/wwwroot/trading-panel-live/www.ency.asia/*
            
            # 创建临时目录用于接收文件
            mkdir -p /tmp/deploy-temp
            
            # 确保临时目录为空
            rm -rf /tmp/deploy-temp/*
      
      - name: Copy build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/tmp/deploy-temp"
          strip_components: 1
          
      - name: Move files and set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 移动文件到正确的位置
            cp -r /tmp/deploy-temp/* /www/wwwroot/trading-panel-live/www.ency.asia/
            
            # 设置正确的权限
            chown -R www:www /www/wwwroot/trading-panel-live/www.ency.asia/
            
            # 清理临时目录
            rm -rf /tmp/deploy-temp
            
            # 重启 Nginx（如果需要）
            /etc/init.d/nginx reload
            
            echo "部署完成！" 