name: Deploy Backend with Docker

on:
  push:
    branches: [ master, main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
      - 'docker-compose.yml'

env:
  # Set the image name, using your GitHub username for the namespace
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/learning-stack-backend

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Grant permission to write to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy to Server
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/www/wwwroot/learning-stack" # Assumes this is your project directory on the server

      - name: Deploy and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the project directory on your server
            cd /www/wwwroot/learning-stack

            # Pull the latest code
            git pull origin master

            # Rebuild and restart the backend service
            docker-compose build --no-cache backend
            docker-compose up -d --no-deps backend

            # Optional: Clean up old, unused Docker images to save disk space
            docker image prune -f

            echo "Backend deployment completed successfully!"