name: Deploy Frontend

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'nginx/**'
      - 'index.html'
      - 'vite.config.js'
      - 'package*.json'
      - 'Dockerfile'
      - '.github/workflows/deploy-frontend.yml'
      - 'docker-compose.yml'
      - 'AI-Protocol-Lab/**'
      - 'docs/**'
      - 'README.md'



jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /www/wwwroot/market-pulse

            # Pull the latest code
            git pull origin master

            # Install dependencies
            npm install

            # Build the frontend
            npm run build

            # Restart nginx to serve the new files
            systemctl reload nginx

            echo "Frontend deployment completed successfully!"