name: Deploy Backend

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build backend
        run: |
          cd backend
          go build -o market-pulse-backend

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "backend/market-pulse-backend"
          target: "/tmp"

      - name: Install and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mv /tmp/backend/market-pulse-backend /www/wwwroot/market-pulse/backend/
            sudo chmod +x /www/wwwroot/market-pulse/backend/market-pulse-backend
            sudo systemctl restart market-pulse 